open module com.mastfrog.numble {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.parameters;
    exports com.mastfrog.parameters.gen;
    exports com.mastfrog.parameters.processor;
    exports com.mastfrog.parameters.validation;
    exports com.mastfrog.parameters.validators;

    // derived from com.fasterxml.jackson.core/jackson-annotations-2.13.2 in com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.pom
    requires transitive com.fasterxml.jackson.annotation;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.mastfrog.acteur.annotations;
    requires transitive com.mastfrog.annotation.processors;
    requires transitive com.mastfrog.annotation.tools;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.tests;

    // derived from com.mastfrog/simplevalidation-1.14 in com/mastfrog/simplevalidation/1.14/simplevalidation-1.14.pom
    requires transitive com.mastfrog.simplevalidation;
    requires java.compiler;
    requires java.logging;

    // derived from javax.inject/javax.inject-1 in javax/inject/javax.inject/1/javax.inject-1.pom
    requires transitive javax.inject.javax.inject;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
