// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.numble.acteur {
    exports com.mastfrog.numble.acteur;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/util-misc-3.0.0-dev
    requires com.mastfrog.misc;

    // Sibling com.mastfrog/numble-3.0.0-dev
    requires com.mastfrog.numble;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from test-source-scan
    requires transitive junit;

}
