open module com.mastfrog.numble.acteur {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.numble.acteur;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.netty.http.test.harness;
    requires transitive com.mastfrog.numble;
    requires transitive com.mastfrog.util.misc;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
